# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jimmy/Bureau/UCL/Advanced_Numerical_Method/LMECA2300-seminar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jimmy/Bureau/UCL/Advanced_Numerical_Method/LMECA2300-seminar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jimmy/Bureau/UCL/Advanced_Numerical_Method/LMECA2300-seminar/CMakeFiles /home/jimmy/Bureau/UCL/Advanced_Numerical_Method/LMECA2300-seminar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jimmy/Bureau/UCL/Advanced_Numerical_Method/LMECA2300-seminar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named anm

# Build rule for target.
anm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 anm
.PHONY : anm

# fast build rule for target.
anm/fast:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/build
.PHONY : anm/fast

#=============================================================================
# Target rules for targets named markers

# Build rule for target.
markers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 markers
.PHONY : markers

# fast build rule for target.
markers/fast:
	$(MAKE) -f deps/BOV/CMakeFiles/markers.dir/build.make deps/BOV/CMakeFiles/markers.dir/build
.PHONY : markers/fast

#=============================================================================
# Target rules for targets named shaderIncludes

# Build rule for target.
shaderIncludes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shaderIncludes
.PHONY : shaderIncludes

# fast build rule for target.
shaderIncludes/fast:
	$(MAKE) -f deps/BOV/CMakeFiles/shaderIncludes.dir/build.make deps/BOV/CMakeFiles/shaderIncludes.dir/build
.PHONY : shaderIncludes/fast

#=============================================================================
# Target rules for targets named bov

# Build rule for target.
bov: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bov
.PHONY : bov

# fast build rule for target.
bov/fast:
	$(MAKE) -f deps/BOV/CMakeFiles/bov.dir/build.make deps/BOV/CMakeFiles/bov.dir/build
.PHONY : bov/fast

#=============================================================================
# Target rules for targets named hello_world

# Build rule for target.
hello_world: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_world
.PHONY : hello_world

# fast build rule for target.
hello_world/fast:
	$(MAKE) -f deps/BOV/CMakeFiles/hello_world.dir/build.make deps/BOV/CMakeFiles/hello_world.dir/build
.PHONY : hello_world/fast

#=============================================================================
# Target rules for targets named lines

# Build rule for target.
lines: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lines
.PHONY : lines

# fast build rule for target.
lines/fast:
	$(MAKE) -f deps/BOV/CMakeFiles/lines.dir/build.make deps/BOV/CMakeFiles/lines.dir/build
.PHONY : lines/fast

#=============================================================================
# Target rules for targets named animation

# Build rule for target.
animation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 animation
.PHONY : animation

# fast build rule for target.
animation/fast:
	$(MAKE) -f deps/BOV/CMakeFiles/animation.dir/build.make deps/BOV/CMakeFiles/animation.dir/build
.PHONY : animation/fast

#=============================================================================
# Target rules for targets named character_table

# Build rule for target.
character_table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 character_table
.PHONY : character_table

# fast build rule for target.
character_table/fast:
	$(MAKE) -f deps/BOV/CMakeFiles/character_table.dir/build.make deps/BOV/CMakeFiles/character_table.dir/build
.PHONY : character_table/fast

#=============================================================================
# Target rules for targets named triangles

# Build rule for target.
triangles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangles
.PHONY : triangles

# fast build rule for target.
triangles/fast:
	$(MAKE) -f deps/BOV/CMakeFiles/triangles.dir/build.make deps/BOV/CMakeFiles/triangles.dir/build
.PHONY : triangles/fast

#=============================================================================
# Target rules for targets named text_style

# Build rule for target.
text_style: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 text_style
.PHONY : text_style

# fast build rule for target.
text_style/fast:
	$(MAKE) -f deps/BOV/CMakeFiles/text_style.dir/build.make deps/BOV/CMakeFiles/text_style.dir/build
.PHONY : text_style/fast

#=============================================================================
# Target rules for targets named koch_snowflake

# Build rule for target.
koch_snowflake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 koch_snowflake
.PHONY : koch_snowflake

# fast build rule for target.
koch_snowflake/fast:
	$(MAKE) -f deps/BOV/CMakeFiles/koch_snowflake.dir/build.make deps/BOV/CMakeFiles/koch_snowflake.dir/build
.PHONY : koch_snowflake/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f deps/BOV/deps/glfw/src/CMakeFiles/glfw.dir/build.make deps/BOV/deps/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f deps/BOV/deps/glad/CMakeFiles/glad.dir/build.make deps/BOV/deps/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

src/SPH.o: src/SPH.c.o

.PHONY : src/SPH.o

# target to build an object file
src/SPH.c.o:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/SPH.c.o
.PHONY : src/SPH.c.o

src/SPH.i: src/SPH.c.i

.PHONY : src/SPH.i

# target to preprocess a source file
src/SPH.c.i:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/SPH.c.i
.PHONY : src/SPH.c.i

src/SPH.s: src/SPH.c.s

.PHONY : src/SPH.s

# target to generate assembly for a file
src/SPH.c.s:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/SPH.c.s
.PHONY : src/SPH.c.s

src/consistency.o: src/consistency.c.o

.PHONY : src/consistency.o

# target to build an object file
src/consistency.c.o:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/consistency.c.o
.PHONY : src/consistency.c.o

src/consistency.i: src/consistency.c.i

.PHONY : src/consistency.i

# target to preprocess a source file
src/consistency.c.i:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/consistency.c.i
.PHONY : src/consistency.c.i

src/consistency.s: src/consistency.c.s

.PHONY : src/consistency.s

# target to generate assembly for a file
src/consistency.c.s:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/consistency.c.s
.PHONY : src/consistency.c.s

src/derivatives.o: src/derivatives.c.o

.PHONY : src/derivatives.o

# target to build an object file
src/derivatives.c.o:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/derivatives.c.o
.PHONY : src/derivatives.c.o

src/derivatives.i: src/derivatives.c.i

.PHONY : src/derivatives.i

# target to preprocess a source file
src/derivatives.c.i:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/derivatives.c.i
.PHONY : src/derivatives.c.i

src/derivatives.s: src/derivatives.c.s

.PHONY : src/derivatives.s

# target to generate assembly for a file
src/derivatives.c.s:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/derivatives.c.s
.PHONY : src/derivatives.c.s

src/kernel.o: src/kernel.c.o

.PHONY : src/kernel.o

# target to build an object file
src/kernel.c.o:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/kernel.c.o
.PHONY : src/kernel.c.o

src/kernel.i: src/kernel.c.i

.PHONY : src/kernel.i

# target to preprocess a source file
src/kernel.c.i:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/kernel.c.i
.PHONY : src/kernel.c.i

src/kernel.s: src/kernel.c.s

.PHONY : src/kernel.s

# target to generate assembly for a file
src/kernel.c.s:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/kernel.c.s
.PHONY : src/kernel.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/main.c.s
.PHONY : src/main.c.s

src/particle.o: src/particle.c.o

.PHONY : src/particle.o

# target to build an object file
src/particle.c.o:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/particle.c.o
.PHONY : src/particle.c.o

src/particle.i: src/particle.c.i

.PHONY : src/particle.i

# target to preprocess a source file
src/particle.c.i:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/particle.c.i
.PHONY : src/particle.c.i

src/particle.s: src/particle.c.s

.PHONY : src/particle.s

# target to generate assembly for a file
src/particle.c.s:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/particle.c.s
.PHONY : src/particle.c.s

src/print_particules.o: src/print_particules.c.o

.PHONY : src/print_particules.o

# target to build an object file
src/print_particules.c.o:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/print_particules.c.o
.PHONY : src/print_particules.c.o

src/print_particules.i: src/print_particules.c.i

.PHONY : src/print_particules.i

# target to preprocess a source file
src/print_particules.c.i:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/print_particules.c.i
.PHONY : src/print_particules.c.i

src/print_particules.s: src/print_particules.c.s

.PHONY : src/print_particules.s

# target to generate assembly for a file
src/print_particules.c.s:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/print_particules.c.s
.PHONY : src/print_particules.c.s

src/utils.o: src/utils.c.o

.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) -f CMakeFiles/anm.dir/build.make CMakeFiles/anm.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... anm"
	@echo "... edit_cache"
	@echo "... markers"
	@echo "... shaderIncludes"
	@echo "... bov"
	@echo "... hello_world"
	@echo "... lines"
	@echo "... animation"
	@echo "... character_table"
	@echo "... triangles"
	@echo "... text_style"
	@echo "... koch_snowflake"
	@echo "... glfw"
	@echo "... glad"
	@echo "... src/SPH.o"
	@echo "... src/SPH.i"
	@echo "... src/SPH.s"
	@echo "... src/consistency.o"
	@echo "... src/consistency.i"
	@echo "... src/consistency.s"
	@echo "... src/derivatives.o"
	@echo "... src/derivatives.i"
	@echo "... src/derivatives.s"
	@echo "... src/kernel.o"
	@echo "... src/kernel.i"
	@echo "... src/kernel.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/particle.o"
	@echo "... src/particle.i"
	@echo "... src/particle.s"
	@echo "... src/print_particules.o"
	@echo "... src/print_particules.i"
	@echo "... src/print_particules.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

